#!/bin/bash
git pull origin master;

cd ../frontend;
npm run build;

cd ../deploy;
ssh -i LightsailDefaultKey-eu-central-1.pem ubuntu@35.159.42.127 "cd ~/voctail && ssh-agent $(git fetch origin && git pull origin master)";
ssh -i LightsailDefaultKey-eu-central-1.pem ubuntu@35.159.42.127 "rm -R ~/voctail/server/frontend_build";
scp -i LightsailDefaultKey-eu-central-1.pem docker-compose.yaml ubuntu@35.159.42.127:~/voctail/docker-compose.yaml;
scp -i LightsailDefaultKey-eu-central-1.pem -r ../frontend/build ubuntu@35.159.42.127:~/voctail/server/frontend_build;
